# Generated by Django 6.1.1 on 2026-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_cycle_length',
            field=models.PositiveIntegerField(blank=True, default=28),
        ),
        migrations.AddField(
            model_name='profile',
            name='average_period_duration',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
