# Generated by Django 6.1.1 on 2026-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='estimated_ovulation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='next_period_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='contraception_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='intercourse_logged',
            field=models.BooleanField(default=False),
        ),
    ]
